env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules:
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  "react/react-in-jsx-scope": 0
  "react/jsx-uses-react": 0
  "no-unused-vars": "warn"
  "no-undef": "warn"
  "prefer-const": "warn"